### ISSUE TITLE
spi_write_and_read() func does not work in version 0.5

### ISSUE THREAD

**Issue by vsethia-adi** [analogdevicesinc/libm2k#294]
I have installed the latest libm2k 0.5 recently to check for the spi_create_buffer func. Error I get is that this functionality does not exist.
AttributeError: module 'libm2k' has no attribute 'spi_create_buffer'

Furtherthe spi_write_and_read() func stops working when called for the second time. It is always waiting for the data to be read back by ADALM2k.

Error message I got is the following, if I disconnect the ADALM2K USB port to break the deadlock.
ERROR: READ LINE: -32
ERROR: READ INTEGER: -32

I reinstalled back the libm2k 0.4 version and I have no issue with the spi_write_and_read() function of the libm2k 0.4 version.
Let me know whether the spi_create_buffer() func is available in the latest version.

**Comment by AlexandraTrifan** [comment]
Hi,

Could you provide the example you are using to make libm2k v0.5.0 crash when calling spi_write_and_read(), in contrast with libm2k v0.4.0? 
Also, could you try to uninstall libm2k and the Python bindings before installing another version and check whether this fixes anything?

The "spi_create_buffer" is not included in the latest development build or the libm2k v0.5.0. It was mentioned in a discussion : https://github.com/analogdevicesinc/libm2k/issues/282 , but it is still a prototype under development.

Thank you!
-Alexandra

**Comment by vsethia-adi** [comment]
Hi Alexandra,
Attached code is working for 0.4.0 but not for 0.5.0.

First spi_write_and_read function executes without any issues. But the next one does not. It hangs indefinitely.

Regards
Vikash

**Comment by AlexandraTrifan** [comment]
I'm sorry, but I can't see any attachment to your reply.

**Comment by vsethia-adi** [comment]
Attaching it as a text file.

**Comment by AlexandraTrifan** [comment]
Thank you!
I'll run some tests and get back to you!

-Alexandra

**Comment by AlexandraTrifan** [comment]
You are using the following setup: `m2k_spi_init.cs_polarity = libm2k.LOW_LEVEL_DIGITAL`
Please initialize the cs_polarity attribute with one of the following values:` cs_polarity - {ACTIVE_LOW | ACTIVE_HIGH}` and let us know if this fixes the issue for you.

-Alexandra

**Comment by vsethia-adi** [comment]
Hi Alexandra,
Yes, this fixes the issue for me.

**Comment by AlexandraTrifan** [comment]
Happy to hear this!
Closing this issue, please let us know if you encounter any other issues with libm2k!

-Alexandra
